[package]
name = "macroific_macro"
version = "3.0.1"
edition = "2021"
rust-version = "1.71.0"
authors = [
  "Art <amolc@pm.me>",
]
license = "Apache-2.0"
readme = "README.md"
description = "Proc macros for the macroific crate"
repository = "https://github.com/Alorel/macroific-rs"
keywords = []
categories = []
include = [
  "src/",
  "Cargo.toml",
]

[lib]
proc-macro = true

[features]
attr_parse = [
  "dep:macroific_attr_parse",
  "macroific_core/generic-impl",
  "macroific_core/module-prefix",
]

[dependencies]
macroific_core = { version = "3.0.1", path = "../macroific-core" }
macroific_attr_parse = { optional = true, version = "3.0.1", path = "../macroific-attr-parse" }

proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
