# https://github.com/Ezard/semantic-prs

enabled: true
commitsOnly: true
types:
  - feat
  - fix
  - docs
  - refactor
  - build
  - ci
  - chore
  - deps
  - perf
scopes:
  - dev
  - core
  - attr_parse
  - macro
