[workspace]
members = ["modules/*"]

[package]
name = "macroific"
description = "Proc macro development utilities"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include.workspace = true

keywords = [
  "macro",
  "development",
  "derive",
  "options",
  "parsing",
]
categories = [
  "development-tools::procedural-macro-helpers",
  "development-tools",
]

[workspace.package]
version = "3.1.0"
edition = "2021"
rust-version = "1.71.0"
authors = [
  "Art <amolc@pm.me>",
]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/Alorel/macroific-rs"
include = ["src/", "Cargo.toml"]

[features]
attr_parse = [
  "macroific_macro/attr_parse",
  "dep:macroific_attr_parse",
  "dep:macroific_macro",
]
attributed = ["macroific_core/attributed"]
full = ["macroific_attr_parse/full"]
generic-impl = ["macroific_core/generic-impl"]
module-prefix = ["macroific_core/module-prefix"]

[dependencies]
macroific_macro = { workspace = true, optional = true }
macroific_attr_parse = { workspace = true, optional = true }
macroific_core = { workspace = true }

[dev-dependencies]
quote = { workspace = true }
proc-macro2 = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }

[workspace.dependencies]
macroific_core = { version = "3.0.1", path = "./modules/macroific-core" }
macroific_attr_parse = { version = "3.0.1", path = "./modules/macroific-attr-parse" }
macroific_macro = { version = "3.0.1", path = "./modules/macroific-macro" }

sealed = "0.7"
proc-macro2 = "1"
quote = "1"
syn = "3"

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[workspace.lints.rustdoc]
redundant_explicit_links = { level = "allow" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
