[package]
name = "macroific_core"
description = "Shared functionality for macroific & macroific_macro"
keywords = []
categories = []
edition.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include.workspace = true

[features]
attributed = []
generic-impl = []
module-prefix = []

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
sealed = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
syn = { workspace = true, features = ["extra-traits"] }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
