[package]
name = "macroific_attr_parse"
description = "Attribute parsing utilities for the macroific crate"
keywords = []
categories = []
edition.workspace = true
rust-version.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
include.workspace = true

[features]
full = ["syn/full"] # implement ParseOption for types requiring `syn/full`

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
sealed = { workspace = true }
syn = { workspace = true }

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
