name: Test
on:
  push:
    branches:
      - master
    paths-ignore:
      - .github/CODE_OF_CONDUCT.md
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/FUNDING.yml
      - LICENSE
      - .gitignore
      - .gitattributes
  pull_request:
    paths-ignore:
      - .github/CODE_OF_CONDUCT.md
      - .github/CODEOWNERS
      - .github/dependabot.yml
      - .github/FUNDING.yml
      - LICENSE
      - .gitignore
      - .gitattributes

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: --deny warnings

jobs:
  unit:
    name: Test on ${{ matrix.toolchain }} with ${{ matrix.features }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - 1.71.0 # min
        features:
          - --all-features
          - ''
          - --features generic-impl
          - --features module-prefix
          - --features attributed
          - --features attr_parse
          - --features "attr_parse full"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        with:
          cache-prefix: v3-test
          cache-suffix: ${{ matrix.features }}
          components: clippy
          toolchain: ${{matrix.toolchain}}
          local: true

      - name: Build
        run: cargo build --locked ${{ matrix.features }}

      - name: Clippy
        run: cargo clippy --locked --workspace --tests --no-deps --examples ${{ matrix.features }}

      - name: Test
        run: cargo test --workspace --locked ${{ matrix.features }}

      - name: Test (examples)
        run: cargo test --examples --locked ${{ matrix.features }}

      - name: Doc
        run: cargo doc --no-deps ${{ matrix.features }} && rm -rf target/doc

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        with:
          cache-prefix: v3-lint
          toolchain: stable
          components: rustfmt
          local: true

      - name: Fmt
        run: cargo fmt --check

      - name: cargo-rdme
        uses: alorel-actions/cargo/rdme@v1

  nightly-test:
    name: Test on nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v1
        with:
          toolchain: nightly-2024-09-29
          cache-prefix: v3-test
          local: true
          components: llvm-tools-preview

      - name: Examples & unit tests
        uses: alorel-actions/cargo/llvm-cov@v1
        with:
          output: unit.lcov
          args: --lcov --examples --tests --workspace --all-features

      - name: Doc tests
        uses: alorel-actions/cargo/llvm-cov@v1
        with:
          output: doc.lcov
          args: --lcov --doctests --workspace --all-features

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          files: unit.lcov doc.lcov

  done:
    name: Preliminary changelog
    runs-on: ubuntu-latest
    needs:
      - unit
      - lint
      - nightly-test
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Changelog
        uses: ./.github/actions/changelog
        continue-on-error: true
